this auta get it
git-svn-id: svn+ssh://192.168.1.9/var/svn/Frita/freeitathenscode@130 243fd332-3cb7-4356-b4cc-f2eb9687c9df

diff --git a/image_scripts/revert_prep_for_shipping_to_eu b/image_scripts/revert_prep_for_shipping_to_eu
--- a/image_scripts/revert_prep_for_shipping_to_eu
+++ b/image_scripts/revert_prep_for_shipping_to_eu
@@ -1,7 +1,7 @@
 #!/bin/bash +x
 if [ 0 -lt $(id |grep -o -P '^uid=\d+' |cut -f2 -d=) ]
 then
-    echo -e "\e[5;31;47mWHA???\e[1;35;47m: Please rerun with sudo or as root\e[0m"
+    echo -e "\e[5;31;40mWHA???\e[1;35;40m: Please rerun with sudo or as root\e[0m"
     exit 4
 fi
 
@@ -10,19 +10,23 @@ Last_RC=0
 ls -l $Trigger_file 2>/dev/null || Last_RC=$?
 if [ $Last_RC -gt 0 ]
 then
-    echo -e "\e[5;31;47mWHA???\e[1;35;47m: can't find $Trigger_file\e[0m"
+    echo -e "\e[5;31;40mWHA???\e[1;35;40m: can't find $Trigger_file\e[0m"
     exit 5
 fi
 
 Last_RC=0
-rm -iv $Trigger_file || Last_RC=$?
-if [ $Last_RC -gt 0 ]
+rm -v $Trigger_file || Last_RC=$?
+if [ $Last_RC -eq 0 ]
 then
-    echo -e "\n\e[1;32;47mSuccess!\e[0m\n"
-    echo -e "\e[1;34;47mPreparing to reboot...\e[0m\n"
+    echo -e "\n\e[1;32;40mSuccess!\e[0m\n"
+    echo -e "\e[1;34;40m10 Seconds to REBOOT...\e[0m\n"
+    sleep 10
     /sbin/shutdown -r now
 else
-    echo -e "\e[5;31;47mWHA???\e[1;35;47m:Something weird is going on. Contact Staff.\e[0m"
-    exit 6
+    echo 'Return Code from Remove command was '$Last_RC
+    echo -e "\e[5;31;40mWHA???\e[1;35;40m:Something weird is going on. Contact Staff.\e[0m"
+    echo -e "\e[1;34;40m60 Seconds to REBOOT...\e[0m\n"
+    sleep 60
+    /sbin/shutdown -r now
 fi
 
